import type { Artifact, Device, Health, PixelAudit, RunDetail, SmokeSuite, TestCase, TestRun } from './types';

export const pixelAudit: PixelAudit = {
  pixelFallback: true,
  fallbackReason: '目标控件未暴露稳定 resource-id、text 或 content-desc，语义定位无法确认唯一节点',
  x: 702,
  y: 1660,
  screenWidth: 1404,
  screenHeight: 1872,
  orientation: 'portrait',
  riskNote: '坐标依赖当前 A2 分辨率与竖屏方向，固件布局或 DPI 变化后可能漂移',
  improvementSuggestion: '建议研发为该控件补充稳定 resource-id 或 content-desc，并在验收后移除像素兜底',
};

export const mockHealth: Health = {
  status: 'degraded',
  adbAvailable: false,
  pythonVersion: '3.12.4',
  artifactRoot: 'artifacts/local-preview',
  checks: [
    {
      id: 'python',
      label: 'Python Runtime',
      status: 'pass',
      detail: '检测到 Python 3.12，可运行本地执行器',
    },
    {
      id: 'adb',
      label: 'ADB Bridge',
      status: 'warn',
      detail: '后端暂不可用，当前展示前端 mock/degraded 状态',
      suggestion: '启动 FastAPI 后重新检测，或确认 Android Platform Tools 已加入 PATH',
    },
    {
      id: 'artifact',
      label: 'Artifact Root',
      status: 'pass',
      detail: '本地预览目录可写，报告证据链可模拟展示',
    },
  ],
};

export const mockDevices: Device[] = [
  {
    id: 1,
    serial: 'A2TEST20260630',
    status: 'online',
    manufacturer: 'AISpeech',
    model: 'A2 Meeting Office Pad',
    androidVersion: '13',
    sdkInt: 33,
    screenWidth: 1404,
    screenHeight: 1872,
    density: 2.0,
    battery: 86,
    network: 'Wi-Fi qa-lab',
    storage: '42.8 GB free',
    adbStatus: 'device',
    lastSeenAt: '2026-06-30 12:58:12',
    capabilities: ['uiautomator2', 'screenshot', 'logcat', 'dump_hierarchy'],
  },
  {
    id: 'device-a2-unauthorized',
    serial: 'A2WAITRSA0002',
    status: 'unauthorized',
    manufacturer: 'AISpeech',
    model: 'A2 Meeting Office Pad',
    androidVersion: '13',
    sdkInt: 33,
    screenWidth: 1404,
    screenHeight: 1872,
    density: 2.0,
    battery: 64,
    network: 'USB attached',
    storage: 'Unknown until authorized',
    adbStatus: 'unauthorized',
    lastSeenAt: '2026-06-30 12:54:03',
    capabilities: ['adb_waiting_authorization'],
  },
];

export const mockCases: TestCase[] = [
  {
    id: 'case-smoke-a2-basic',
    name: '基础真机操作检查',
    type: 'smoke',
    priority: 'P0',
    tags: ['ADB', 'smoke', 'A2'],
    status: 'enabled',
    description: '验证 A2 真机下拉通知、返回、截图、logcat 与报告证据闭环',
    hasPixelFallback: false,
    pixelFallbackCount: 0,
    updatedAt: '2026-06-30 12:40:16',
    steps: [
      { id: 's1', name: '打开通知栏', action: 'open_notification', timeoutSec: 10 },
      { id: 's2', name: '返回桌面', action: 'keyevent', params: { key: 'BACK' }, timeoutSec: 5 },
      { id: 's3', name: '采集截图', action: 'screenshot', timeoutSec: 10 },
      { id: 's4', name: '采集 logcat', action: 'logcat_snapshot', params: { durationSec: 3 }, timeoutSec: 10 },
    ],
  },
  {
    id: 'case-pixel-risk-audit',
    name: '会议按钮像素兜底审计',
    type: 'regression',
    priority: 'P0',
    tags: ['pixel-fallback', 'audit'],
    status: 'enabled',
    description: '语义定位失败时保留像素兜底风险链路，验证报告风险显性展示',
    hasPixelFallback: true,
    pixelFallbackCount: 1,
    updatedAt: '2026-06-30 12:46:51',
    steps: [
      {
        id: 'p1',
        name: '点击会议入口兜底坐标',
        action: 'pixel_tap',
        timeoutSec: 10,
        pixelAudit,
      },
      { id: 'p2', name: '断言会议页标题', action: 'semantic_assert', selector: { text: '会议记录' }, timeoutSec: 20 },
    ],
  },
];

export const mockSmokeSuite: SmokeSuite = {
  suite: {
    id: 'p0_smoke',
    name: 'A2 P0 冒烟套件',
    tag: 'p0_smoke',
    priority: 'P0',
    description: '覆盖 A2 真机 artifact 链路、基础安全动作和 Pixel Fallback 审计链路。',
    tags: ['a2', 'p0', 'smoke', 'p0_smoke', 'suite:p0_smoke'],
  },
  ready: true,
  cases: mockCases,
  caseIds: [101, 102],
  caseCount: mockCases.length,
  pixelFallbackCount: mockCases.reduce((sum, item) => sum + item.pixelFallbackCount, 0),
  requiresRiskAcceptance: true,
  acceptanceNotes: [
    '本套件包含 Pixel Fallback 审计链路验证用例。',
    '执行前需确认当前设备分辨率、方向与套件审计说明一致。',
    '坐标兜底仅用于审计链路验证，稳定业务用例应优先补充 resource-id 或 content-desc。',
  ],
};

export const mockRuns: TestRun[] = [
  {
    id: 'run-20260630-001',
    status: 'failed',
    deviceId: 1,
    deviceSerial: 'A2TEST20260630',
    totalCount: 2,
    passedCount: 1,
    failedCount: 1,
    skippedCount: 0,
    startedAt: '2026-06-30 13:02:10',
    endedAt: '2026-06-30 13:04:28',
    reportPath: 'artifacts/run-20260630-001/report/index.html',
    pixelFallbackCount: 1,
  },
  {
    id: 'run-20260630-000',
    status: 'passed',
    deviceId: 1,
    deviceSerial: 'A2TEST20260630',
    totalCount: 1,
    passedCount: 1,
    failedCount: 0,
    skippedCount: 0,
    startedAt: '2026-06-30 12:42:04',
    endedAt: '2026-06-30 12:43:11',
    reportPath: 'artifacts/run-20260630-000/report/index.html',
    pixelFallbackCount: 0,
  },
];

export const mockArtifacts: Artifact[] = [
  {
    id: 'artifact-shot-001',
    runId: 'run-20260630-001',
    resultId: 'result-pixel-001',
    deviceId: 1,
    type: 'screenshot',
    path: 'artifacts/run-20260630-001/A2TEST20260630/pixel_audit_after.png',
    mimeType: 'image/png',
    sizeBytes: 248120,
    checksum: 'sha256:9f2a-local-preview',
    createdAt: '2026-06-30 13:03:08',
    meta: { title: '像素兜底后截图', pixelAudit },
  },
  {
    id: 'artifact-logcat-001',
    runId: 'run-20260630-001',
    resultId: 'result-logcat-001',
    deviceId: 1,
    type: 'logcat',
    path: 'artifacts/run-20260630-001/A2TEST20260630/logcat.txt',
    mimeType: 'text/plain',
    sizeBytes: 90562,
    checksum: 'sha256:74bb-local-preview',
    createdAt: '2026-06-30 13:03:20',
    meta: {
      title: 'logcat snapshot',
      content: '06-30 13:03:17.421 I TestOps: start action=pixel_tap serial=A2TEST20260630\n06-30 13:03:18.004 W Locator: semantic selector unavailable, pixel fallback audited\n06-30 13:03:20.115 E Assert: text=会议记录 not found code=52002',
      pixelAudit,
    },
  },
  {
    id: 'artifact-report-001',
    runId: 'run-20260630-001',
    deviceId: 1,
    type: 'report',
    path: 'artifacts/run-20260630-001/report/index.html',
    mimeType: 'text/html',
    sizeBytes: 18240,
    checksum: 'sha256:report-local-preview',
    createdAt: '2026-06-30 13:04:28',
    meta: { title: '运行报告摘要', content: '失败 1 / 通过 1，包含截图、logcat、UI XML 与像素兜底风险摘要。' },
  },
];

export const mockRunDetail: RunDetail = {
  run: mockRuns[0],
  results: [
    {
      id: 'result-smoke-001',
      runId: 'run-20260630-001',
      caseId: 'case-smoke-a2-basic',
      caseName: '基础真机操作检查',
      status: 'passed',
      durationMs: 43118,
      message: '完成通知栏、返回、截图与 logcat 证据采集',
      locatorStrategy: 'evidence',
      pixelFallbackUsed: false,
      startedAt: '2026-06-30 13:02:12',
      endedAt: '2026-06-30 13:02:55',
    },
    {
      id: 'result-pixel-001',
      runId: 'run-20260630-001',
      caseId: 'case-pixel-risk-audit',
      caseName: '会议按钮像素兜底审计',
      status: 'failed',
      durationMs: 92306,
      errorCode: 52002,
      message: '像素兜底点击后语义断言 text=会议记录 超时',
      locatorStrategy: 'pixel_fallback',
      pixelFallbackUsed: true,
      startedAt: '2026-06-30 13:02:56',
      endedAt: '2026-06-30 13:04:28',
      pixelAudit,
    },
  ],
  artifacts: mockArtifacts,
};
